# Exibe o código das cidades brasileiras
#!/bin/bash

echo       "ESTADO         CÓDIGO"
 #echo"-----------------------------"
 #echo"-----------------------------"
echo       "Acre(AC)              68"       
echo       "Alagoas(AL)           82" 
echo       "Amapá(AP)             96"
echo       "Amazonas(AM)          92,97"
echo       "Bahia(BA)             71,73,74,75,77"
echo       "Ceará(CE)             85, 88"
echo       "Espírito Santo(ES)    27,28"
echo       "Goiás(GO)             61,62,64"
echo       "Maranhão(MA)          98,99"
echo       "Mato Gross(MT)        65,66"
echo       "M Grosso Do sul(MS)   67"
echo       "Minas Gerais(MG)      31,32,33,34,35,37,38"
echo       "Pará(PA)              91,93,94"
echo       "Paraíba(PB)           83" 
echo       "Paraná(PR)            41,42,43,44,45,46"
echo       "Pernambuco(PE)        81,87"
echo       "Piaui(PI)             86,89"
echo       "Rio de Janeiro(RJ)    21,22,24"
echo       "R Grande do Norte(RN) 84" 
